import {Shell,PageIntro,CTA} from '../venue';
import {ShieldCheck,CalendarDays,Heart,Flower2,Utensils,Ban,Check} from 'lucide-react';
export const metadata={title:'Rental Policies'};
const cards=[
{icon:Heart,title:'Eligibility & approval',items:['Church members and non-members are welcome. Reservations are subject to venue approval.','The renter must be at least 21 years old and legally authorized to enter into the agreement.','Guest count must stay within the maximum capacity set by the venue.']},
{icon:CalendarDays,title:'Reservation & payment',items:['A signed rental agreement and non-refundable booking deposit are required to secure your date. Deposit amounts are confirmed by the venue.','Pay the remaining balance no later than 14 days before the event. Late payment may result in cancellation.','Time beyond the agreed rental period is billed at $50 per hour.']},
{icon:ShieldCheck,title:'Security deposit & damage',items:['The security deposit is separate from the non-refundable booking deposit.','Damage to facilities, furniture, or equipment is deducted from the security deposit. The renter must pay any balance exceeding that deposit within a reasonable time.','The security deposit is returned within 7 days after the event if there are no damages or violations.']},
{icon:CalendarDays,title:'Cancellation & refunds',items:['30 days or more before the event: the booking deposit is non-refundable; the remaining balance may be refunded.','Less than 30 days before the event: no refunds will be issued.','If the venue cancels because of unforeseen circumstances, all renter payments will be refunded.']},
{icon:Flower2,title:'Decorations, setup & cleanup',items:['Decorations must not damage walls, ceilings, floors, or furniture. No nails, screws, staples, glue, or damaging tape.','Glitter, confetti, rice, fake petals, and similar materials are not permitted.','Candles, open flames, sparklers, fog machines, and special effects require prior written approval.','Remove all decorations, personal items, and rentals by the end of the rental period. Complete cleanup by the next day.','Leave the venue as received. Bag trash properly and place it in the dumpster at the back of the parking lot.']},
{icon:Utensils,title:'Food, catering & alcohol',items:['Outside catering is allowed unless the venue specifies otherwise.','The kitchen is for warming and serving only unless prior approval is given.','Alcohol requires written approval and service by a licensed bartender. The venue may stop service or end the event for violations.','Illegal substances are strictly prohibited.']},
{icon:ShieldCheck,title:'Safety, conduct & liability',items:['The renter is responsible for all guests, vendors, and service providers and must comply with venue rules, fire codes, and safety regulations.','Responsible adults must supervise children at all times. Music must remain at acceptable levels.','Use the venue only for the event in the agreement. Offices, storage rooms, and the sanctuary are restricted.','The venue is not responsible for lost, stolen, or damaged personal property.','The renter agrees to hold harmless ICFC Assembly of God and Asenso Hall Event Center from claims, injuries, losses, or damages arising from the event or guests and vendors.','Confirm any event-specific insurance needs and emergency arrangements with the venue team. The agreement does not specify a general insurance requirement.']},
{icon:Ban,title:'Prohibited activities',items:['No smoking or vaping inside the building.','Weapons, illegal activity, illegal substances, and disorderly conduct are strictly prohibited.','Unauthorized access to restricted areas is prohibited.','The venue may immediately end an event without a refund when rules are violated.']}
];
const faqs=[['Can non-members rent Asenso Hall?','Yes. Church members and non-members are welcome, subject to venue approval.'],['When is my date secured?','After approval, a signed rental agreement, and the required non-refundable booking deposit. Submitting a reservation request alone does not hold a date.'],['What is the difference between the deposits?','The booking deposit secures the event date and is non-refundable. The separate security deposit covers damage or violations and is returned within 7 days when the conditions are met.'],['Can we bring our own caterer?','Outside catering is permitted unless the venue specifies otherwise. Kitchen use is limited to warming and serving unless approved in advance.'],['When do we need to clean up?','The agreement requires cleanup by the next day. Decorations, personal items, and rentals must be removed by the end of your rental period. Confirm your exact access and cleanup schedule with the venue.'],['What is the guest capacity?','The venue team will confirm the maximum capacity and seating arrangements for your event. Your guest count must not exceed that approved capacity.'],['Can we use candles or serve alcohol?','Candles, open flames, and special effects need prior written approval. Alcohol also requires written approval and must be served by a licensed bartender.'],['Is insurance required?','The supplied agreement does not state a general insurance requirement. Ask the venue about any event-specific requirements.']];
export default function Policies(){return <Shell><PageIntro label="CLEAR GUIDELINES. PEACE OF MIND." title="Rental Policies" text="A little planning helps every gathering run smoothly. Please review these guidelines before requesting your date."/><section className="section"><div className="policy-top"><p>Based on the Asenso Hall Venue Rental Agreement. The signed agreement governs your rental; Ohio law applies.</p><a className="button outline" href="mailto:info@icfcassembly.org?subject=Request%20rental%20agreement">Request Rental Agreement</a></div><div className="policy-grid">{cards.map(({icon:Icon,title,items})=><article className="card policy-card" key={title}><Icon size={27}/><h2>{title}</h2><ul>{items.map(t=><li key={t}>{t}</li>)}</ul></article>)}</div></section><section className="section tinted"><div className="center"><span className="eyebrow">GOOD TO KNOW</span><h2>Frequently Asked Questions</h2></div><div className="faqs">{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section><CTA/></Shell>}
